### ISSUE TITLE
q40+dir file size doesn’t match the uncompressed size in the prefix header of the corresponding compressed file

### ISSUE THREAD

**Issue by yash-puligundla** [samtools/htscodecs#37]
As per rANS 4x8, the four bytes starting from byte 5 of the compressed file give the uncompressed length. But this does not add up for the test file "q40+dir".

- the size of the raw input file, htscodecs/tests/dat/q40+dir = 102000 bytes

- uncompressed size from the prefix header of compressed file (htscodecs/tests/dat/r4x8/q40+dir.0, htscodecs/tests/dat/r4x8/q40+dir.1 and htscodecs/tests/dat/r4x16/q40+dir.0) = 100000 bytes

@jkbonfield, Ideally, the two sizes should match and it does for the other test files (q4, q8, qvar). 
Could you please help me figure out if I am missing any steps or if the file is not as expected?

**Comment by yash-puligundla** [comment]
Thank you, @jkbonfield. Is this true for all the test files or just the q40+dir file?

**Comment by jkbonfield** [comment]
It's only the q40+dir that has the additional column, but all are newline oriented.  Typically when we're compressing a block in CRAM we don't have the newlines there, but CRAM does know the read lengths so this is also used again in the fqzcomp codec.  It exploits the fact that some technologies reduce quality as the sequence gets longer, so the number of bases since the start of the read is a useful thing to factor in to quality value probabilities
